name: Release

on:
  push: {}
  pull_request: {}
  # push:
  #   tags:
  #     - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Build Wheel
        shell: bash
        run: echo $0 && just build-wheel

      - name: Zip Frontend
        working-directory: ./frontend
        run: just zip-frontend

      # This upload step is only for testing, to see if the artifacts got built
      # correctly even though we're not uploading them in a release.
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: executable
          path: |
            dist/*.whl
            frontend/frontend.zip

      - name: Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.whl
            frontend/frontend.zip
            Changelog.md
            Readme.md
          body: See Readme.md for usage instructions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
